# -*- coding: utf-8 -*-
"""Ridge Regression_L2_.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17MI3EPthgBYjeFJKg9VscHqC1OrMnK5d
"""

import pandas as pd
BHNames= ['crim','zn','indus','chas','nox','rm',
         'age','dis','rad','tax','ptratio','black','lstat','medv']


url='https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
data = pd.read_csv(url, delim_whitespace=True, names=BHNames)

print(data.head(20))


'''
CRIM: Per capita crime rate by town
ZN: Proportion of residential land zoned for lots over 25,000 sq. ft
INDUS: Proportion of non-retail business acres per town
CHAS: Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
NOX: Nitric oxide concentration (parts per 10 million)
RM: Average number of rooms per dwelling
AGE: Proportion of owner-occupied units built prior to 1940
DIS: Weighted distances to five Boston employment centers
RAD: Index of accessibility to radial highways
TAX: Full-value property tax rate per $10,000
PTRATIO: Pupil-teacher ratio by town
B: 1000(Bk — 0.63)², where Bk is the proportion of [people of African American descent] by town
LSTAT: Percentage of lower status of the population
MEDV: Median value of owner-occupied homes in $1000s'''



from sklearn.model_selection import train_test_split

X = data.drop('medv', axis = 1)
print('X shape = ',X.shape)
Y = data['medv']
print('Y shape = ',Y.shape)

from sklearn import linear_model
import matplotlib.pyplot as plt

names = data.drop('medv', axis =1).columns
print(names)

lasso = linear_model.Lasso(alpha=0.2)

lasso_coef = lasso.fit(X,Y).coef_

plt.plot(range(len(names)),lasso_coef )
plt.xticks(range(len(names)), names, rotation=60)
plt.ylabel("coefficient")
plt.show()





#For Ridge
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_std = scaler.fit_transform(X)

from sklearn.linear_model import Ridge
ridge = Ridge(alpha=0.2)

model = ridge.fit(x_std,Y).coef_

model

















'''
rr = Ridge(alpha=0.4)
rr.fit(X_std, Y)

plt.scatter(X_std, Y)
plt.plot(X_std, c='red')

plt.plot(model.coef_,linestyle='none',marker='o',markersize=10,color='green')
plt.xlabel('Coefficient Index',fontsize=16)
plt.ylabel('Coefficient Magnitude',fontsize=16)
plt.legend(fontsize=13,loc=4)
plt.show()'''

